### ISSUE TITLE
"webr": "0.2.1"

### ISSUE THREAD

**Issue by peter100u** [georgestagg/webr-nextjs-example#1]
I used "webr": "0.2.1" to depend, it happened, error, could not be found, why

![image](https://github.com/georgestagg/webr-nextjs-example/assets/14010579/ea1eed03-446d-49cf-946c-ed8a0fd196ec)

"dependencies": {
    "@types/node": "20.6.1",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "next": "13.4.19",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2",
    "webr": "0.2.1"
  }

code

import {WebR} from "webr/webr-main";
import {RDouble} from "webr/robj-main";

const webR = new WebR({
    baseUrl: './node_modules/webr/dist/',
});

async function getRandomNumbers() {
    await webR.init();
    const result = await webR.evalR('rnorm(25,10,10)') as RDouble;
    try {
        return await result.toArray();
    } finally {
        webR.destroy(result);
    }
}

**Comment by peter100u** [comment]
Please ask if you need to update the latest version of shi li ...

**Comment by georgestagg** [comment]
Thanks for reporting this issue, sorry it's taken me a while to get around to it.

I've updated the example in 79a151fc91b0818feecddcd451bd932a2724e7d6 to use the newer webR v0.2.1. Pulling the latest commit from the repo should now work for you.
