### ISSUE TITLE
Guidance on Vercel builds & deployment

### ISSUE THREAD

**Issue by uhuggins** [georgestagg/webr-nextjs-example#2]
Thank you for the Nextjs starter with WebR. Excited to see the possibilities of using R in the browser! 

Writing if there is any guidance on building/deploying with Vercel. Locally it works well and builds beautifully, however the Vercel build fails to locate the `baseUrl: './node_modules/webr/dist/'` and errors out with a 500. 

I suspect this is due to Vercel's bundling/webpack behaviour. A similar issue exists for [Pyodide](https://github.com/vercel/next.js/issues/45478)

 This is more of a question than an issue. Thanks again for all of the examples 😅

**Comment by georgestagg** [comment]
I've updated the `next.config.js` file in the latest commit so that the support files in `./node_modules/webr/dist` are deployed alongside the app. With this, Nextjs apps with webR should be able to be deployed to Vercel.

Example: https://webr-nextjs-example-iota.vercel.app

**Comment by uhuggins** [comment]
Thank you @georgestagg . Works like a charm!
